### ISSUE TITLE
ReferenceError: pluginName is not defined

### ISSUE THREAD

**Issue by davisford** [scott-morris/gulp-json-refs#2]
Hiya,

Just tried your plugin, but it throws the following err:

```
/Users/davis/git/giftcard/doc/api/node_modules/gulp-json-refs/index.js:47
  return new PluginError(pluginName, file.path + ': ' + msg, {
                         ^
ReferenceError: pluginName is not defined
    at File.createError (/Users/davis/git/giftcard/doc/api/node_modules/gulp-json-refs/index.js:47:26)
    at trycatch (/Users/davis/git/giftcard/doc/api/node_modules/gulp-json-refs/index.js:26:12)
    at DestroyableTransform.json_res [as _transform] (/Users/davis/git/giftcard/doc/api/node_modules/gulp-json-refs/index.js:68:20)
    at DestroyableTransform.Transform._read (/Users/davis/git/giftcard/doc/api/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/davis/git/giftcard/doc/api/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/davis/git/giftcard/doc/api/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:335:12)
    at writeOrBuffer (/Users/davis/git/giftcard/doc/api/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:321:5)
    at DestroyableTransform.Writable.write (/Users/davis/git/giftcard/doc/api/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:248:11)
    at write (/Users/davis/git/giftcard/doc/api/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/davis/git/giftcard/doc/api/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
```

For the following gulp task `resolveRefs`, note that the `default` task `buildPublicAPI` does work:

``` javascript
/* jshint node: true */
'use strict';

var gulp = require('gulp'),
  resolve = require('json-refs').resolveRefs,
  YAML = require('yaml-js'),
  path = require('path'),
  jsonRefs = require('gulp-json-refs'),
  fs = require('fs');

gulp.task('default', ['buildPublicAPI']);

gulp.task('buildPublicAPI', function () {
  // json-refs resolver doesn't seem to work unless it is in the base dir of the files
  process.chdir(path.join(__dirname, 'src'));
  var root = YAML.load(fs.readFileSync('public.yaml').toString());
  var options = {
    resolveLocalRefs: true,
    processContent: function (content) {
      return YAML.load(content);
    }
  };

  resolve(root, options).then(function (results) {
    console.log('YAML dump \n\n', YAML.dump(results.resolved));
  });
});

gulp.task('resolveRefs', function() {
  return gulp.src('src/*.yaml')
    .pipe(jsonRefs())
    .pipe(gulp.dest('dist'));
});

```

**Comment by scott-morris** [comment]
This is my bad, I prematurely posted this before it was ready and forgot about the project.  I'll clean this up tonight.

**Comment by davisford** [comment]
Cool -- I saw you posted a new version.  I need YAML support too.  I might send a PR to add that after I have a chance to try out the new version.

**Comment by davisford** [comment]
I'm a bit pressed on time, and I know this is fairly lame  ...I should do a proper PR with test updates, but if you want quick YAML support, this seems to work:

``` javascript
// this is a gulp plugin wrapper around json-refs 

var es = require("event-stream");
var clone = require("clone");
var YAML = require("yaml-js");
var JsonRefs = require("json-refs");

function getJsonMatch (filePath) {
  if (typeof filePath === "string") {
    return filePath.match(/.json$/);
  }
}

function getYamlMatch (filePath) {
  if (typeof filePath === "string") {
    return filePath.match(/.yaml$/);
  }
}

module.exports = function(opts) {
  "use strict";
  opts = opts || {};

  function resolveRefs(file, callback) {
    var options = clone(opts);

    if (file.isNull()) {
      return callback(null, file);
    }

    if (options.yaml) {
      if (!getYamlMatch(file.path)) {
        return callback(null, file);
      }
    } else if (!getJsonMatch(file.path)) {
      return callback(null, file);
    }

    // If location not specified, set it to the file's folder for relative references to work
    if (!options.location) {
      options.location = file.path.split("/").slice(0,-1).join("/");
    }

    if (options.yaml) {
      JsonRefs.resolveRefs(YAML.load(file.contents), options).then(function (results) {
        file.contents = new Buffer(YAML.dump(results.resolved));
        callback(null, file);
      }, function (error) {
        callback();
      });
    } else {
      JsonRefs.resolveRefs(JSON.parse(file.contents), options).then(function (results) {
        file.contents = new Buffer(JSON.stringify(results.resolved));
        callback(null, file);
      }, function (error) {
        callback();
      });
    }
  }

  return es.map(resolveRefs);
};
```

**Comment by scott-morris** [comment]
I've tried a variation on the code you've posted and the tests aren't passing yet, so I'll see if I can get this to work in my spare time.

**Comment by davisford** [comment]
FWIW, this is how I'm using it...

``` javascript
/* jshint node: true */
'use strict';

var gulp = require('gulp'),
  path = require('path'),
  YAML = require('yaml-js'),
  resolver = require('./resolver');

gulp.task('default', ['resolveRefs']);

var options = {
  location: path.resolve(__dirname, 'src'),
  yaml: true,
  depth: 0,
  resolveLocalRefs: false,
  processContent: function (content) {
    return YAML.load(content);
  }
};

gulp.task('resolveRefs', function() {
  return gulp.src('src/*.yaml')
    .pipe(resolver(options))
    .pipe(gulp.dest('dist'));
});
```

**Comment by scott-morris** [comment]
Ok, I got the tests to work, assuming that the local file refs are JSON files and not YAML referencing YAML.

**Comment by davisford** [comment]
:+1:
